spring:
  application:
    name: Healthx

  logging:
    level:
      br.healthX.Healthx: INFO

  config:
    import: optional:file:./.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/healthX
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

api:
  security:
    token:
      secret: ${JWT_SECRET:mySecretKey}
